# Generated by Django 4.0.2 on 2022-03-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('idno', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Number')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('phno', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
